name: GNU Windows extension extractor for GitHub Actions

on:
  push:
    branches:
      - 19.1.4

permissions:
  contents: write
  pull-requests: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Tar for Extraction
        run: sudo apt install -y xz-utils tar

      - name: Obtain source code from https://repo.msys2.org/mingw/sources/
        run: |
          wget https://repo.msys2.org/mingw/sources/mingw-w64-llvm-19.1.4-1.src.tar.zst

      - name: Extract Source Code into Root Directory
        run: |
          tar --strip-components=1 -xf mingw-w64-llvm-19.1.4-1.src.tar.zst
          tar --strip-components=1 -xf llvm-19.1.4.tar.gz

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          rm mingw-w64-llvm-19.1.4-1.src.tar.zst
          rm llvm-19.1.4.tar.gz
          rm .gitignore || true
          rm -rf .github/workflows/*.yml || true
          git add .
          git commit -m "GNU Windows extension extractor for GitHub Actions"
          git push
